language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - pypy
  - pypy3

install:
  # Install the codecov library
  - pip install codecov

script:
  # Upgrade pytest and py to avoid version conflicts
  - pip install -U pytest py

  # Run all unit tests and flake8 checks
  - python setup.py test

after_success:
  # Send coverage statistics to codecov
  codecov

notifications:
  # Disable email notifications if something fails
  email: false
